import { PUBLIC_GITHUB_REPO_URL, PUBLIC_SHADCN_URL, PUBLIC_SITE_URL } from 'astro:env/server'

// Constants
export const SITE_URL = PUBLIC_SITE_URL
export const GITHUB_REPO_URL = PUBLIC_GITHUB_REPO_URL
export const SHADCN_URL = PUBLIC_SHADCN_URL
